services:
    vinabb.emojismilies.decorates.text_formatter.s9e.renderer:
        class: vinabb\emojismilies\decorates\textformatter\s9e\renderer
        decorates: text_formatter.s9e.renderer
        arguments:
            - '@cache.driver'
            - '%text_formatter.cache.dir%'
            - '%text_formatter.cache.renderer.key%'
            - '@text_formatter.s9e.factory'
            - '@dispatcher'
            - '@language'
        calls:
            - [configure_quote_helper, ['@text_formatter.s9e.quote_helper']]
            - [configure_smilies_path, ['@config', '@path_helper']]
            - [configure_user, ['@user', '@config', '@auth']]
    vinabb.emojismilies.listener:
        class: vinabb\emojismilies\event\listener
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@language'
        tags:
            - { name: event.listener }
