services:
    vinabb.groupicons.listener:
        class: vinabb\groupicons\event\listener
        arguments:
            - '@dbal.conn'
            - '@cache.driver'
            - '@user'
            - '@template'
            - '@request'
            - '@ext.manager'
            - '@path_helper'
        tags:
            - { name: event.listener }
